Explore courses button padding fixed
PiyushKalyanpy/GyanaGuru pull request #165
Opened 2023-05-25 05:35 UTC by muhammedanaskhan

2023-05-27 19:09 UTC, lalitmee requested changes

2023-05-27 19:09 UTC, lalitmee commented on Components/HeroSection.tsx
> +                <h4 className="text-xl  font-archivo">Explore Courses</h4>
please remove the extra space in between

2023-05-27 19:09 UTC, lalitmee commented on Components/HeroSection.tsx
> +                <span className="inline-flex bg-black "></span>
please remove the extra space before `"`

2023-05-27 19:09 UTC, lalitmee commented
@muhammedanaskhan, can you please update your PR description with a screenshot of the before and after changes?

2023-05-29 06:56 UTC, PiyushKalyanpy commented
@muhammedanaskhan please add the issue number to the description

2023-06-09 09:31 UTC, PiyushKalyanpy commented
The requested changes have not been implemented, so we are closing this pull request. Please feel free to resubmit the changes when they are ready.

2023-06-09 09:31 UTC, closed without merging