Fix Issue#28
PiyushKalyanpy/GyanaGuru pull request #172
Opened 2023-05-25 18:32 UTC by MOHDNEHALKHAN

@PiyushKalyanpy, I have added the right-padding side of the Explore Courses Button 
Before Changes - 
![Screenshot 2023-05-26 000156](https://github.com/PiyushKalyanpy/GyanaGuru/assets/125626654/5db3df7d-07c0-40be-b7a2-56fe7889bc6e)
After Changes -
![Screenshot 2023-05-26 000031](https://github.com/PiyushKalyanpy/GyanaGuru/assets/125626654/290c24f8-e2ee-426a-ab24-d68ebbe27657)

2023-05-27 18:46 UTC, lalitmee requested changes

2023-05-27 18:46 UTC, lalitmee commented on Components/HomeSidebar.tsx
> +      {/* Top Part  */}
No need of the comments in HTML part. Please remove all the comments from HTML in this file.

2023-05-27 18:46 UTC, lalitmee commented on Components/HeroSection.tsx
> +                className="flex flex-row items-center gap-4 p-4 text-white bg-black border-2 border-black rounded-full h-fit cursor-pointer dark:bg-zinc-50 pr-7"
don't add padding to make it align in the center.

Just use flex properties as its already using `flex`

2023-05-27 18:46 UTC, lalitmee commented on package-lock.json
> -      "integrity": "sha512-pPwaZt+SPOshK8xNoiQlK5XIrS97kFYc3Rc7xmy373QsOJ9MmqXxLaYssP5Kcds4wd2qK//amx/c+A8O2fVeZA=="
don't push `package-lock.json` if you haven't installed a new package in `package.json`

2023-05-27 18:46 UTC, lalitmee commented on Components/HomeSidebar.tsx
> +      <div className="flex flex-col items-start gap-[24px] p-0 w-[304px] h-[360px] top-[207px] left-[calc(50%-152px)] absolute">
What are these changes? There is nothing about these in the PR description. Please, always try to explain a little bit about your changes in the PR description.

2023-05-27 18:46 UTC, lalitmee commented on Components/LogoWithName.tsx
> +    <div className="flex flex-row items-center p-0 gap-6 w-[230px] h-[49px] top-[43px] left-[37px] justify-center absolute">
Can you please add `before` and `after` screenshots of all the UI changes?

2023-06-12 03:33 UTC, PiyushKalyanpy commented
The changes requested were not done, so we acre closing this PR, please reopen the PR once you made the changes.

2023-06-12 03:33 UTC, closed without merging