Feature request template added
PiyushKalyanpy/GyanaGuru pull request #186
Opened 2023-05-26 16:55 UTC by Tushar98644

fixes #162 

@PiyushKalyanpy Kindly review....

2023-05-26 19:32 UTC, lalitmeeq reviewed
Hey @Tushar98644, can you please share some screenshots or the text preview of this? How is it looking?

And, instead of tagging the people in your comment just tag the people in the reviewers section. 
Check this [doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review#:~:text=Under%20your%20repository%20name%2C%20click,to%20their%20username%2C%20click%20Request.).

2023-05-27 09:39 UTC, Tushar98644 commented
> Hey @Tushar98644, can you please share some screenshots or the text preview of this? How is it looking?
> 
> And, instead of tagging the people in your comment just tag the people in the reviewers section. Check this [doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review#:~:text=Under%20your%20repository%20name%2C%20click,to%20their%20username%2C%20click%20Request.).

<img width="1355" alt="Screenshot 2023-05-27 at 2 57 15 PM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/107763774/c8d2286f-e9cc-4445-813e-4887b4fe5950">

I don't think the repository permissions allow for a contributor to request a review , you need to be a collaborator or have write permissions , please confirm from your end

2023-05-27 18:27 UTC, lalitmee requested changes

2023-05-27 18:27 UTC, lalitmee commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +title: "[Feature] <write a small description here>"
Lets not add `[Feature]` here as we can always assign the labels to the issue.

Can we make a `label` of type `feature` and then automate that label to automatically attach with the feature in this template?

2023-05-27 18:27 UTC, lalitmee commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +labels: ["enhancement", "goal: addition"]
Add `feature` label here. Check the `labels` in the issues section. I have created a new `feature` label.

2023-05-27 18:27 UTC, lalitmee commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        - label: "I have read the [Contributing Guidelines]"
Can we add the link to the `CONTRIBUTING.md` file here?

2023-05-27 18:27 UTC, lalitmee commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +      description: A clear and concise description of any alternative solution or features you've considered.
I think there should be two `textarea`, one for the feature description and other one for the alternative solutions of things they have tried.

2023-06-12 03:33 UTC, PiyushKalyanpy commented
The changes requested were not done, so we acre closing this PR, please reopen the PR once you made the changes.

2023-06-12 03:33 UTC, closed without merging