[FEAT] Custom Error Page 404 #58
PiyushKalyanpy/GyanaGuru pull request #191
Opened 2023-05-26 20:05 UTC by virajchandra51

Added the Custom Error Page 404.
It has a Go Back Option that pops the last url from the router stack as well as a navbar and an imported landingfooter.
This is how it looks.

<img width="1440" alt="Screenshot 2023-05-27 at 1 31 16 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/95118745/1f7a3f3f-312e-413a-adf1-444ff2af7e2a">

2023-05-27 18:07 UTC, lalitmee commented
@virajchandra51, please check this [doc](https://cbea.ms/git-commit/) on how to add good commits. And then please change the commit message which you have currently `404error`.

Soon we will be improving our contributions guidelines so that it is clear before starting on the issue.

2023-05-27 18:36 UTC, lalitmee requested changes

2023-05-27 18:36 UTC, lalitmee commented on pages/404.tsx
> +        {/* Logo with Title */}
Lets not add these comments

2023-05-27 18:36 UTC, lalitmee commented on pages/404.tsx
> +        {/* Get Started Button */}
don't need comments for this, as it is not a hard to read code.

2023-05-27 18:36 UTC, lalitmee commented on pages/404.tsx
> +        <Image alt="404error" src='/images/pagenotfound.png' width={900} height={500}></Image>
Instead of using an image we should create the 404 text in our code as the image loading and storing can be a problem.

2023-05-27 18:36 UTC, lalitmee commented on pages/404.tsx
> +  const handleClick = () => {
```suggestion
  const redirectToHome = () => {
```

The function name should be descriptive.

2023-05-27 18:36 UTC, lalitmee commented on pages/404.tsx
> +  const handleBack = () => {
```suggestion
  const handleGoBack = () => {
```

2023-05-27 18:36 UTC, lalitmee commented on package-lock.json
> -      "integrity": "sha512-pPwaZt+SPOshK8xNoiQlK5XIrS97kFYc3Rc7xmy373QsOJ9MmqXxLaYssP5Kcds4wd2qK//amx/c+A8O2fVeZA=="
No need to push `package-lock.json` if you haven't added a new package in `package.json`. Please discard these changes.

2023-05-29 18:57 UTC, virajchandra51 commented
@lalitmee I have made the changes.

2023-05-30 03:56 UTC, PiyushKalyanpy requested changes

2023-05-30 03:56 UTC, PiyushKalyanpy commented on package-lock.json
please remove this file from PR

2023-05-30 04:30 UTC, lalitmee requested changes
@virajchandra51, I don't see the changes which I have asked for. Please don't use an image for showing the `404` status on the page. Create your own page using `HTML` and `CSS`. 

Please remove the `package-lock.json` and `public/images/pagenotfound.png` files from your PR.

2023-05-30 05:17 UTC, closed without merging

2023-05-30 05:37 UTC, virajchandra51 commented
@PiyushKalyanpy Can I contact you? Need some help on this.

2023-05-30 05:46 UTC, virajchandra51 commented
@lalitmee Can I contact you? Need some help on this.