Bug Fixed
PiyushKalyanpy/GyanaGuru pull request #198
Opened 2023-05-27 20:28 UTC by vishnubansal001

As the issue raised by me that the section below the navbar which is saying in the marquee type tag that join us etc etc is not showing when we are scrolling down and when we scroll up it is showing so this is being resolved in this pull request

2023-05-30 03:54 UTC, PiyushKalyanpy commented
Please add issue number in description of PR

2023-05-30 04:20 UTC, lalitmee requested changes

2023-05-30 04:20 UTC, lalitmee commented on pages/index.tsx
> +  // useEffect(() => {
Why are we commenting out this code?

2023-05-30 04:20 UTC, lalitmee commented on package-lock.json
> +        "react-toastify": "^9.1.3",
Don't push `package-lock.json` file if you haven't installed any new package in `package.json`

2023-05-30 04:23 UTC, lalitmee commented
> As the issue raised by me that the section below the navbar which is saying in the marquee type tag that join us etc etc is not showing when we are scrolling down and when we scroll up it is showing so this is being resolved in this pull request

@ vishnubansal001, that is the desired behavior right now. If someone scrolls down it means they want to see more so we can hide the navbar and as they scroll up we can show the navbar again.

@PiyushKalyanpy, please confirm this and close this PR, if this behavior is desired.

2023-06-12 03:35 UTC, PiyushKalyanpy commented
Hey @vishnubansal001 , we have designed it like this only. So that the user can view the full page view by removing obstruction (marquee element : in this case)

2023-06-12 03:35 UTC, closed without merging