Added Bug/Issue and documentation template
PiyushKalyanpy/GyanaGuru pull request #217
Opened 2023-05-29 13:34 UTC by DivyanshiNarang

Resolves issue #192 

Added files for:

* Bug / Issue template
* Documentation template

"Thank you for giving me this opportunity"

Please review it. @PiyushKalyanpy

2023-05-29 13:58 UTC, PiyushKalyanpy requested changes

2023-05-29 13:58 UTC, PiyushKalyanpy commented on .github/workflow/ISSUE_TEMPLATE/documentation.yml
> +title: "[DOCS] <description>"
```suggestion
title: "[DOCS]:"
```
You can remove ` <description>`  from the title and add a colon after brackets.

2023-05-29 13:58 UTC, PiyushKalyanpy commented on .github/workflow/ISSUE_TEMPLATE/documentation.yml
> +    id: extrainfo
```suggestion
    id: extra-info
```

2023-05-29 13:58 UTC, PiyushKalyanpy commented on .github/workflow/ISSUE_TEMPLATE/bug_report.yml
We appreciate your hard work, but we have already added a bug report template and we are not aligned with these changes, so you can please remove this file.

2023-05-29 14:05 UTC, DivyanshiNarang commented on .github/workflow/ISSUE_TEMPLATE/bug_report.yml
Okay sure.

2023-05-29 14:11 UTC, DivyanshiNarang commented
I did the changes you mentioned above. Please review it again. @PiyushKalyanpy

2023-05-30 03:26 UTC, PiyushKalyanpy approved these changes
Thank you @DivyanshiNarang for your valuable contribution 🎉. We would like to have more contributions from you to the Gyanaguru project.

2023-05-30 03:26 UTC, merged