Integrated gitpod
PiyushKalyanpy/GyanaGuru pull request #223
Opened 2023-05-29 22:28 UTC by akash19coder

Closes/ Fixes: #201

Description: Added a `.gitpod.yml` file

2023-05-30 04:26 UTC, lalitmee requested changes

2023-05-30 04:26 UTC, lalitmee commented on .gitpod.yml
> +# This configuration file was automatically generated by Gitpod.
@akash19coder, what extra will I be able to do after this PR gets merged?

2023-05-30 04:26 UTC, lalitmee commented on package-lock.json
> +      "integrity": "sha512-pPwaZt+SPOshK8xNoiQlK5XIrS97kFYc3Rc7xmy373QsOJ9MmqXxLaYssP5Kcds4wd2qK//amx/c+A8O2fVeZA==",
Why are we committing this file if there is no new package being installed?

2023-06-09 09:40 UTC, PiyushKalyanpy commented
The requested changes have not been implemented, so we are closing this pull request. Please feel free to resubmit the changes when they are ready.

2023-06-09 09:40 UTC, closed without merging