Updated link of Our Services in footer
PiyushKalyanpy/GyanaGuru pull request #253
Opened 2023-05-31 17:06 UTC by ShubhaSwarup

## Description 📝
Updated link of Our Services in footer 

Fixes: <link>#253
[Updated link of Our Services in footer]
## Changes 💬

- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.

## Checklist ✅

- [✅] Reviewed the code changes thoroughly.
- [ ] Tested the changes locally and ensured they work as expected.
- [✅ ] Updated relevant documentation.
- [ ] Added appropriate test cases, if applicable.
- [ ] Considered potential security or performance implications.
- [ ✅] Code adheres to the project's style guidelines.
- [✅ ] Addressed all reviewer comments and concerns, if any.

## Screenshots (if applicable)

Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***

2023-06-01 02:29 UTC, PiyushKalyanpy commented
Please update the issue link in the description

2023-06-01 05:32 UTC, lalitmee requested changes
The PR description formatting is not correct. Please fix that too.

2023-06-01 05:32 UTC, lalitmee commented on Components/LandingFooter.tsx
> +                <Link href="/OurServices.txs" className={hoverEffect}>Our Services</Link>
Is this a valid URL?

2023-06-27 11:43 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.

2023-06-27 11:43 UTC, closed without merging