Navigation to Homepage by clicking on logo
PiyushKalyanpy/GyanaGuru pull request #254
Opened 2023-06-01 06:46 UTC by itsPriyanshuhere

## Description 📝

fix issue number #274
Any click on the logo would navigate the user to the home page. Hover effect was added which changes the cursor to points as the user hovers over the logo.

## Changes 💬

Used react router to navigate by pushing "/"  using router.push("/").
Used tailwind css to convert the cursor to pointer as user hovers over it.

## Checklist ✅

- [ ] Reviewed the code changes thoroughly.
- [ ] Tested the changes locally and ensured they work as expected.
- [ ] Updated relevant documentation.
- [ ] Added appropriate test cases, if applicable.
- [ ] Considered potential security or performance implications.
- [ ] Code adheres to the project's style guidelines.
- [ ] Addressed all reviewer comments and concerns, if any.

## Additional Notes 📒

This would make the navigation easy for user if they want to redirect to home page.

2023-06-05 19:06 UTC, lalitmee requested changes
Revert `package-lock.json` changes. Those are not required.

2023-06-05 19:06 UTC, lalitmee commented on Components/LogoWithName.tsx
> +    <div className="flex  items-center   w-full h-fit  justify-center cursor-pointer " onClick={handleClickonLogo}>
Please put proper html attributes as we are putting `onClick` on a `div`.

2023-06-27 11:44 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.

2023-06-27 11:44 UTC, closed without merging

2023-06-27 11:47 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.