firebase file changed. also did some changes in LandingContact page.
PiyushKalyanpy/GyanaGuru pull request #258
Opened 2023-06-01 17:18 UTC by shivaniyuvrajyadav

## Description 📝
#220 
email through sign up is not working properly . 

## Changes 💬

- added emailjs to send emails 
- 

## Checklist ✅

- [ .] Reviewed the code changes thoroughly.
- [ .] Tested the changes locally and ensured they work as expected.
- [ .] Updated relevant documentation.
- [ .] Added appropriate test cases, if applicable.
- [. ] Considered potential security or performance implications.
- [ .] Code adheres to the project's style guidelines.
- [ .] Addressed all reviewer comments and concerns, if any.

## Screenshots (if applicable)

Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***

2023-06-01 17:41 UTC, lalitmee requested changes
Please add a proper description in your PR about why and what are you using to achieve the desired behaviour

2023-06-01 17:41 UTC, lalitmee commented on Components/LandingContact.tsx
> +      .sendForm('service_rjqxpou', 'template_f8vouol', form.current, 'o2kgKJm8TdvQP4pBr')
```suggestion
      .sendForm('service_rjqxpou', 'template_f8vouol', form.current, 'o2kgKJm8TdvQP4pBr')
```
Please document the things here using comments as these are hard-to-understand things.

2023-06-05 19:09 UTC, lalitmee approved these changes
@PiyushKalyanpy, LGTM, but I would request you to check this first in your local.

2023-06-07 06:21 UTC, PiyushKalyanpy commented on firebase/index.tsx
Remove this file from PR

2023-06-07 06:21 UTC, PiyushKalyanpy commented on Components/LandingContact.tsx
We think that integrating email.js in or project is not a good option because of its pricing.

What you can do then ?
You can save the contact form data to firebase realtime database. 

Please let us know if you want to continue working on this,
 you can open a new issue for that.

2023-06-07 09:00 UTC, shivaniyuvrajyadav commented on Components/LandingContact.tsx
@PiyushKalyanpy I want to work on this issue i.e. to store data from Firebase.

2023-06-07 17:49 UTC, closed without merging