Benefits in footer, leading to why choose us page
PiyushKalyanpy/GyanaGuru pull request #266
Opened 2023-06-03 21:18 UTC by vishwabandita

Earlier, the "benefits" section in footer was leading to the home page as no url was attached to href, now I have added the url to "why choose us" page which correctly leads to the desired content.

## Changes 💬

- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.

## Checklist ✅

- [✅] Reviewed the code changes thoroughly.
- [✅] Tested the changes locally and ensured they work as expected.
- [✅] Updated relevant documentation.
- [✅] Added appropriate test cases, if applicable.
- [✅] Considered potential security or performance implications.
- [✅] Code adheres to the project's style guidelines.
- [✅] Addressed all reviewer comments and concerns, if any.

2023-06-04 09:12 UTC, lalitmee requested changes

2023-06-04 09:12 UTC, lalitmee commented on Components/LandingFooter.tsx
> +                <Link href="/WhyChooseUs" className={hoverEffect}>Benefits</Link>
We use not use `cameCase` in the urls.
```suggestion
                <Link href="/why-choose-us" className={hoverEffect}>Benefits</Link>
```

2023-06-04 09:12 UTC, lalitmee commented on package.json
> +  "main": "next.config.js",
what are these changes?

2023-06-27 11:47 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.

2023-06-27 11:47 UTC, closed without merging