Fix redirect to course page
PiyushKalyanpy/GyanaGuru pull request #276
Opened 2023-06-05 12:36 UTC by jibola2588

## Description 📝
redirect to the courses page from home page  

## Changes 💬

I added routing to the course page when the user clicks on courses on the navigation bar

## Checklist ✅

- [ ] Reviewed the code changes thoroughly.
- [ ] Tested the changes locally and ensured they work as expected.
- [ ] Updated relevant documentation.
- [ ] Added appropriate test cases, if applicable.
- [ ] Considered potential security or performance implications.
- [ ] Code adheres to the project's style guidelines.
- [ ] Addressed all reviewer comments and concerns, if any.

## Screenshots (if applicable)
![Screenshot (101)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/76418445/6dc32594-ae86-454e-9ada-3ed188805182)

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***

2023-06-05 18:54 UTC, lalitmee requested changes
remove `pacakge-lock.json` changes

2023-06-06 11:47 UTC, jibola2588 commented on package-lock.json
this file has been removed

2023-06-07 06:34 UTC, PiyushKalyanpy commented
Your code changes should not look like this, please create a new PR instead.
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/1b171c7a-84fc-4169-9848-8597905e25f8)

2023-06-08 07:59 UTC, jibola2588 commented
> Your code changes should not look like this, please create a new PR instead. ![image](https://user-images.githubusercontent.com/79275157/243939773-1b171c7a-84fc-4169-9848-8597905e25f8.png)

okay, I will make a new PR, and close this PR

2023-06-15 18:31 UTC, closed without merging