Checkbox
PiyushKalyanpy/GyanaGuru pull request #290
Opened 2023-06-07 18:13 UTC by parasss19

## Description 📝

Added the checkboxes in issue template

2023-06-08 02:55 UTC, PiyushKalyanpy commented
Why you have removed the PR template ?? Why there is no issue number in the description ?? and why are you not following the contribution guidelines ??

2023-06-08 02:59 UTC, PiyushKalyanpy requested changes

2023-06-08 02:59 UTC, PiyushKalyanpy commented on .github/ISSUE_TEMPLATE/bug.yml
This is not the correct way of adding the checkboxes. for all the files. I have provided the code here, please update the code for other template also.
```
- type: checkboxes
    id: terms
    attributes:
      label: 'Record'
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

        - label: I'm a GSSoC'23 contributor

        - label: I want to work on this issue

```

2023-06-08 02:59 UTC, PiyushKalyanpy commented on tailwind.config.js
Please remove this file from PR.

2023-06-08 03:36 UTC, parasss19 commented on .github/ISSUE_TEMPLATE/bug.yml
> This is not the correct way of adding the checkboxes. for all the files. I have provided the code here, please update the code for other template also.
> 
> ```
> - type: checkboxes
>     id: terms
>     attributes:
>       label: 'Record'
>       options:
>         - label: I agree to follow this project's Code of Conduct
>           required: true
> 
>         - label: I'm a GSSoC'23 contributor
> 
>         - label: I want to work on this issue
> ```

Hi @PiyushKalyanpy i will make all the required changes I'm outside right now. Thanks for the suggestions

2023-06-15 18:31 UTC, PiyushKalyanpy commented
Please share the screenshot (preview) of the updated template. 
You can test it on your own GitHub repository.

2023-06-16 06:53 UTC, parasss19 commented
> Please share the screenshot (preview) of the updated template. You can test it on your own GitHub repository.

HI @PiyushKalyanpy I added the checkboxes in issues template and due to some YAML error i have to make some changes due to which there are so many commits but now its added properly.

<img width="960" alt="2023-06-16" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/101205226/9293d381-1468-4b5d-9417-777c301b9f8f">

2023-06-16 20:24 UTC, PiyushKalyanpy commented
Please add an appropriate title to the pull request.

2023-06-17 02:23 UTC, parasss19 commented
> Please share the screenshot (preview) of the updated template. You can test it on your own GitHub repository.

Change the title of PR 
Resolved the issue #285

2023-06-17 02:50 UTC, PiyushKalyanpy commented on tailwind.config.js
please remove this file also

2023-06-17 17:31 UTC, PiyushKalyanpy commented
please create a new pr.

2023-06-17 17:32 UTC, parasss19 commented
> please create a new pr.

Oki I will create new PR with new branch 👍

2023-06-17 17:37 UTC, closed without merging