dark mode issue#272 solved
PiyushKalyanpy/GyanaGuru pull request #296
Opened 2023-06-08 14:26 UTC by mandliyarajendra11

## Description 📝

The sign-up page did not have a dark mode toggle component, and apart from that, if the website is in dark mode and you go to the sign-up page, some text was not visible due to certain classes.

## Changes 💬

I added the dark mode toggle component and made some changes in the CSS classes, adding some css class related to dark mode . Now, the dark mode option has been successfully added to it .

## Checklist ✅

- [ ] Reviewed the code changes thoroughly.
- [ ] Tested the changes locally and ensured they work as expected.
- [ ] Updated relevant documentation.
- [ ] Added appropriate test cases, if applicable.
- [ ] Considered potential security or performance implications.
- [ ] Code adheres to the project's style guidelines.
- [ ] Addressed all reviewer comments and concerns, if any.

## Screenshots (if applicable)

before when you on dark mode - 
![Screenshot (114)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/022305cd-9602-4b3f-a792-6d4fcb1becc1)

now  - 
![Screenshot (115)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/09254900-c279-4ef8-9f6e-ece02588763d)

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***

fixed  #272

2023-06-08 17:17 UTC, lalitmee requested changes
@mandliyarajendra11 
- add some screenshots of the changes in the pages
- remove the `package-lock.json` file from your file changes, as it is not required here.

2023-06-09 04:53 UTC, mandliyarajendra11 commented
@lalitmee check now

2023-06-09 17:21 UTC, mandliyarajendra11 commented
@PiyushKalyanpy  merge

2023-06-11 06:46 UTC, PiyushKalyanpy requested changes

2023-06-11 06:46 UTC, PiyushKalyanpy commented on database/firebase.tsx
Do not include this file in PR.

2023-06-11 06:46 UTC, PiyushKalyanpy commented on package-lock.json
You don't have to delete this file. 
Please make a new PR instead.
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/b4ab913b-c642-45df-9e6a-695b477551c6)

2023-06-11 06:56 UTC, mandliyarajendra11 commented on package-lock.json
okay

2023-06-11 06:59 UTC, mandliyarajendra11 commented on package-lock.json
> You don't have to delete this file. Please make a new PR instead. ![image](https://user-images.githubusercontent.com/79275157/244918671-b4ab913b-c642-45df-9e6a-695b477551c6.png)

@PiyushKalyanpy 
check PR #306

2023-06-11 09:38 UTC, closed without merging