#322 : Right Sidebar dark theme issue resolved
PiyushKalyanpy/GyanaGuru pull request #325
Opened 2023-06-16 07:50 UTC by 1mazin

## Description 📝
The right sidebar in the dashboard is now supporting dark theme.

## Screenshots (if applicable)

Before
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/78849132/e9882ff3-d94a-4e7c-a321-e7dde714b11f)

After
![changed](https://github.com/PiyushKalyanpy/GyanaGuru/assets/78849132/f22e2ff2-53f6-460b-8c19-e5a21a841a3a)

## Additional Notes 📒
I want to contribute under gssoc23

2023-06-16 21:41 UTC, PiyushKalyanpy requested changes

2023-06-16 21:41 UTC, PiyushKalyanpy commented on Components/RightSideBar/Calendar.tsx
>            <IndividualDate date={13} day="T" isTodayDate={false} />
Update the color classes for these buttons also, when hovering a button.

2023-06-17 02:19 UTC, 1mazin commented
Could you please check now.

2023-06-17 02:52 UTC, PiyushKalyanpy requested changes

2023-06-17 02:52 UTC, PiyushKalyanpy commented on database/firebase.tsx
remove this file from PR

2023-06-17 02:52 UTC, PiyushKalyanpy commented on package-lock.json
remove this file

2023-06-17 05:23 UTC, PiyushKalyanpy commented
Please create a new pr, I think by mistake you have pushed those files which are not required and removed the required files.

2023-06-17 05:50 UTC, 1mazin commented
I have created a new pull request for the same. Could you please review that.

2023-06-17 06:32 UTC, closed without merging