contact section is updated now on nav bar
PiyushKalyanpy/GyanaGuru pull request #363
Opened 2023-06-21 05:10 UTC by Sushilverma002

## Description 📝

Fixes/Closes: #294 
contact section is updated now on nav bar
## Changes 💬

- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.

## Screenshots (if applicable)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114687502/10e1dbea-ba92-4e87-a879-5fb53400e8af)

Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers. 
***Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it.***

2023-06-21 12:19 UTC, PiyushKalyanpy requested changes

2023-06-21 13:23 UTC, Sushilverma002 commented on Components/LandingPage/LandingNav.tsx
> +  };
sir everything seem to be correct but it doesn't move smoothly similar in our service section it not going smooth but still it was their.

2023-06-23 08:56 UTC, Sushilverma002 commented
updated please check @PiyushKalyanpy

2023-06-27 11:50 UTC, PiyushKalyanpy commented
You have referred to the wrong Issue!!

2023-06-27 12:02 UTC, Sushilverma002 commented
I am unable to detect where I'm going wrong. Smoothness while scrolling is not working properly. Otherwise everything seems fit.

2023-06-30 12:56 UTC, lalitmee requested changes

2023-07-08 16:02 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.

2023-07-08 16:02 UTC, closed without merging