Making new
PiyushKalyanpy/GyanaGuru pull request #385
Opened 2023-06-22 06:07 UTC by bhavyanarnoli

## Description 📝

#329
## Changes 💬
 vanilla tilt only in the Landingpage

## Screenshots (if applicable)

<img width="738" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/108413315/232ec129-278e-482c-8142-d882a01fa1f7">
<img width="712" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/108413315/632a5f18-2f1c-426e-b6bd-ac9fb809c306">

## Additional Notes 📒

only commiting changed files

2023-06-22 06:24 UTC, bhavyanarnoli commented
@PiyushKalyanpy i have done all the changes pls see my pr

2023-06-22 06:24 UTC, bhavyanarnoli commented
@lalitmee

2023-06-22 07:19 UTC, bhavyanarnoli commented
i have not made any change in firebase just one line got added by mistake, please conside my pr

2023-06-22 07:19 UTC, bhavyanarnoli commented
![Uploading image.png…]()

2023-06-22 07:20 UTC, bhavyanarnoli commented
done under gssoc

2023-06-27 12:26 UTC, PiyushKalyanpy approved these changes

2023-06-27 14:09 UTC, bhavyanarnoli commented
@PiyushKalyanpy why cant i see the conflicts

2023-06-27 16:58 UTC, bhavyanarnoli commented
ill do it in a while pls don't close the pull request

2023-06-30 12:54 UTC, lalitmee requested changes

2023-06-30 12:54 UTC, lalitmee commented on Components/LandingPage/WhyChooseUs.tsx
> +        <div className="col-span-4 grid grid-cols-3 gap-8 backgroundColor:grey dark : backgroundColor: #F7EDE3">
What are we trying to do here?

2023-07-08 16:03 UTC, PiyushKalyanpy commented
Hey there, 
We are closing this pull request as the changes we requested were not implemented. Please create a new PR once you implement the changes.

2023-07-20 19:32 UTC, merged

2023-07-20 19:35 UTC, PiyushKalyanpy commented
Hey @bhavyanarnoli , your valuable contribution is appreciated, and we've merged the PR after resolving conflicts. For your next contribution, please check #466 to push only the required file. Also, there are new issues opened; feel free to check them out.

2023-07-27 06:37 UTC, bhavyanarnoli commented
thank you!