ESLint rules added
PiyushKalyanpy/GyanaGuru pull request #416
Opened 2023-06-27 12:36 UTC by Nikhil1017

As per issue #410

2023-06-27 12:37 UTC, Nikhil1017 commented
@PiyushKalyanpy

2023-06-27 12:43 UTC, Nikhil1017 commented
It has successfully deployed now

2023-06-27 15:37 UTC, lalitmee requested changes

2023-06-27 15:37 UTC, lalitmee commented on .eslintrc.json
> +    "no-unused-vars": "warn"
@PiyushKalyanpy and @Nikhil1017 please check these rules too.
```js
  rules: {
    'prettier/prettier': ['error', prettierOptions],
    'arrow-body-style': [2, 'as-needed'],
    'class-methods-use-this': 0,
    'import/imports-first': 0,
    'import/newline-after-import': 0,
    'import/no-dynamic-require': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default': 0,
    'import/no-webpack-loader-syntax': 0,
    'import/prefer-default-export': 0,
    indent: [2, 2, { SwitchCase: 1 }],
    'max-len': 0,
    'newline-per-chained-call': 0,
    'no-confusing-arrow': 0,
    'no-console': 1,
    'no-unused-vars': 2,
    'no-use-before-define': [
      'error',
      { functions: false, classes: false, variables: true },
    ],
    'prefer-template': 2,
    'require-yield': 0,
  },

```

2023-06-27 15:37 UTC, lalitmee commented on components/RightSideBar/Notes.tsx
> +type NotesCard = {
Leave an empty line after imports

2023-06-28 11:39 UTC, Nikhil1017 commented
@lalitmee thanks for your suggestions, I have incorporated the rules and put blank line near import, you can check now

2023-06-29 05:48 UTC, Nikhil1017 commented
@Vaishnavi2701-mk

2023-06-30 12:51 UTC, lalitmee approved these changes

2023-07-01 06:39 UTC, Nikhil1017 commented
@lalitmee conflicts resolved

2023-07-04 15:43 UTC, lalitmee approved these changes

2023-07-08 13:28 UTC, Nikhil1017 commented
@PiyushKalyanpy

2023-07-08 16:04 UTC, PiyushKalyanpy approved these changes

2023-07-08 16:09 UTC, PiyushKalyanpy commented
Hey @Nikhil1017 , Thank you 🎉for your valuable contribution.

2023-07-08 16:09 UTC, merged

2023-07-08 16:56 UTC, Nikhil1017 commented
thanks @PiyushKalyanpy