Node Package Manager version enforced
PiyushKalyanpy/GyanaGuru pull request #418
Opened 2023-06-27 12:56 UTC by Nikhil1017

as per #413

2023-06-27 15:39 UTC, lalitmee requested changes

2023-06-27 15:39 UTC, lalitmee commented on components/RightSideBar/Notes.tsx
> +type NotesCard = {
Leave an empty line after imports

2023-06-28 11:47 UTC, Nikhil1017 commented on components/RightSideBar/Notes.tsx
> +type NotesCard = {
@lalitmee Thanks, I have left emty line now

2023-06-29 05:49 UTC, Nikhil1017 commented
@Vaishnavi2701-mk

2023-06-30 12:48 UTC, lalitmee approved these changes

2023-07-01 07:17 UTC, Nikhil1017 commented
@lalitmee conflicts resolved

2023-07-03 04:14 UTC, PiyushKalyanpy requested changes

2023-07-03 04:14 UTC, PiyushKalyanpy commented on components/depricated/RightSideBar/IndividualDate.tsx
>        <div
Have you mentioned these changes in your issue #413  ?? If not please revert back the changes for all the files that were not mentioned in issue #413

2023-07-03 04:14 UTC, PiyushKalyanpy commented on components/depricated/RightSideBar/Notes.tsx
remove all the unnecessary files from the pr and keep only three files : 
1. .npmrc
2. .eslint.json
3. package.json

2023-07-03 04:14 UTC, PiyushKalyanpy commented on package-lock.json
create a new pr which should only contain the above mentioned files.

2023-07-05 09:39 UTC, Nikhil1017 commented
@PiyushKalyanpy I have modified the existing pull request to only include those 3 files. I have opened issue #450 addressing the changes to other files and pull request #451 solving the issue.

2023-07-08 13:29 UTC, Nikhil1017 commented
@PiyushKalyanpy

2023-07-08 16:04 UTC, closed without merging