Second
PiyushKalyanpy/GyanaGuru pull request #468
Opened 2023-07-08 18:08 UTC by pavitrachavda97

## Description 📝

Closes: #392 
Added Scroll to top button

## Changes 💬
- Created ScrollToTop in components
- Created ScrollToTopPage inside ScrollToTopfolder
- Added ScrollToTop component in index.tsx

## Screenshots (if applicable)
Light Mode:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/91004608/bc1e4925-8b9a-42b9-8940-49037d823a7e)

Dark Mode:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/91004608/50b6c119-a4bd-40d4-ad2b-233f62a31838)

2023-07-09 18:33 UTC, PiyushKalyanpy requested changes

2023-07-09 18:33 UTC, PiyushKalyanpy commented on components/ScrollToTop/ScrollToTopPage.tsx
> +};
Please use tailwind css instead of this.

2023-07-09 18:33 UTC, PiyushKalyanpy commented on package-lock.json
Remove this file. 
#466

2023-07-09 18:33 UTC, PiyushKalyanpy commented on components/ScrollToTop/ScrollToTopPage.tsx
> +      &uarr;
User google material icons here. 
`<span className="material-symbols-outlined>{icon name}</span>`

2023-07-09 18:33 UTC, PiyushKalyanpy commented on components/ScrollToTop/ScrollToTopPage.tsx
Move this file from ScrollToTop folder to Utils folder inside compoenents.

2023-07-10 12:54 UTC, pavitrachavda97 commented
@PiyushKalyanpy 
I have made the requested changes. The changes have been committed and pushed to the repository. Please review the updated code and let me know if any further adjustments are needed. Thank you!

2023-07-20 18:44 UTC, closed without merging