Improved loading of the Website
PiyushKalyanpy/GyanaGuru pull request #486
Opened 2023-07-16 14:34 UTC by parasss19

## Description 📝

- Fixes/Closes: #485
- Earlier the images are in png/jpg format which requires more space and loading time
- I go through each and every folder and changed all images to webp without breaking any image

## Changes 💬

- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.

## Screenshots (if applicable)

### Loading Time difference (images)
### 1 Original
<img width="956" alt="Screenshot 2023-07-16 194812" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/101205226/493a8374-d2a9-4f64-9c94-8b49802e8111">

### 2 Updated
<img width="960" alt="time loading " src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/101205226/870b8ff7-6b25-43a1-a490-cf37aac084c1">

2023-07-16 18:23 UTC, PiyushKalyanpy requested changes

2023-07-16 18:23 UTC, PiyushKalyanpy commented on package-lock.json
Please remove this file from PR, refer #466

2023-07-17 06:00 UTC, parasss19 commented
Hey @PiyushKalyanpy I removed the package-lock.json file 
- Please provide level2 or level3 as it require changes in so many files
- And also i have to go through each and every files to change around 150+ images

2023-07-17 09:33 UTC, PiyushKalyanpy commented
I will add the label once I merge the pull request.

2023-07-17 09:35 UTC, PiyushKalyanpy commented
> Hey @PiyushKalyanpy I removed the package-lock.json file 
> - Please provide level2 or level3 as it require changes in so many files
> - And also i have to go through each and every files to change around 150+ images

Please create a new pr without that file, your pr should not look like (more than 8000 deletions) you can refer the discussion tab

2023-07-20 18:33 UTC, closed without merging