Routing fixed
PiyushKalyanpy/GyanaGuru pull request #525
Opened 2023-07-21 16:00 UTC by Vidip-Ghosh

## Description 📝

Fixes/Closes: #507 
Improved

## Changes 💬

- I have used async rewrite feature of NextJS to make the route. 

**Before:**
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/91741581/ca60f073-4d07-4866-b665-e3073a0345cc)

**After:**
<img width="757" alt="Screenshot 2023-07-21 at 21 29 57" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/91741581/942b47f0-f5ac-4b50-9018-5c8ba485091b">

## Screenshots (if applicable)

https://github.com/PiyushKalyanpy/GyanaGuru/assets/91741581/c5ae1b9f-d5e3-49bf-b10c-942224570c98

## Additional Notes 📒

Include any additional information or context that might be helpful for the reviewers.
**_Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it._**

2023-07-21 17:11 UTC, lalitmee approved these changes

2023-07-22 03:55 UTC, PiyushKalyanpy requested changes

2023-07-22 03:55 UTC, PiyushKalyanpy commented on next.config.js
add other routes too.

2023-07-22 03:55 UTC, PiyushKalyanpy commented on package.json
remove both the package file and make a new pr. Check this out #466

2023-07-22 06:39 UTC, closed without merging