implementing new design to faq page
PiyushKalyanpy/GyanaGuru pull request #553
Opened 2023-07-24 14:08 UTC by s2sharpit

## Description 📝

Closes: #480 

## Changes 💬

- Implementing new design to faq page.

2023-07-24 20:37 UTC, PiyushKalyanpy requested changes

2023-07-24 20:37 UTC, PiyushKalyanpy commented on package-lock.json
remove this file

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +          <p className="text-lg font-medium">
add more margin : top and button

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +          <span className="material-icons">search</span>
use cursor-pointer

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +          <button className="border px-4 py-2 rounded-xl">Contact Us</button>
on click go to home page contact us form

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +            Learn More
on click go to about us page for now

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +          alt=""
add alt text - screenshot of gyanaguru website

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +      <div className="pb-8 w-full lg:w-[50%]">
remove all the hardcoded values and replace them by tailwind classes 
like  : `w-1/2` in this case

2023-07-24 20:37 UTC, PiyushKalyanpy commented on src/pages/static/faq.tsx
> +          <span className="material-icons">search</span>
in all material icons, replace `material-icons` class with `material-symbols-outlined`

2023-07-25 03:16 UTC, s2sharpit commented on src/pages/static/faq.tsx
> +          <p className="text-lg font-medium">
Hey @PiyushKalyanpy,
Is it good now?

2023-07-25 03:24 UTC, s2sharpit commented
Hey @PiyushKalyanpy,
I have made the changes. Please review it and if needed some more changes let me know.

2023-07-26 17:40 UTC, PiyushKalyanpy requested changes

2023-07-26 17:40 UTC, PiyushKalyanpy commented on package-lock.json
please remove this file

2023-07-26 17:41 UTC, merged